### ISSUE TITLE
Finetune Issue Tensor 的dim 对应不上

### ISSUE THREAD

**Issue by makeme-zgz** [zhenhao-huang/CPM-1-Finetune-Text-Generation#1]
File "/home/ubuntu/cpm/mpu/transformer.py", line 132, in forward
    attention_scores = torch.mul(attention_scores, ltor_mask) - \
RuntimeError: The size of tensor a (36) must match the size of tensor b (648) at non-singleton dimension 3

**Comment by zhenhao-huang** [comment]
您可以提供更详细的错误信息吗

**Comment by makeme-zgz** [comment]
替换了deepspeed的版本之后就没有这个问题了。 0.3.15 的deepspeed是可以的
